name: Push or Pull

on: [push, pull_request]

env: 
    push_msg: "C'est un push !"
    pull_msg: "C'est une pull request !"

jobs:
  job_push:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push'}}
    steps:
      - name: 'Push'
        run: echo "$push_msg"

  job_pull:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request'}}
    steps:
     - name: 'Pull'
       run: echo "$pull_msg"